const List<Map<String, dynamic>> jointsData = [
  {
    "name": "Base",
    "code": "7s",
    "minAngle": 15.0,
    "maxAngle": 165.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Base",
    "code": "1s",
    "minAngle": 15.0,
    "maxAngle": 165.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Shoulder",
    "code": "8s",
    "minAngle": 15.0,
    "maxAngle": 165.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Shoulder",
    "code": "2s",
    "minAngle": 15.0,
    "maxAngle": 165.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Elbow",
    "code": "9s",
    "minAngle": 0.0,
    "maxAngle": 160.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Elbow",
    "code": "3s",
    "minAngle": 0.0,
    "maxAngle": 160.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Wrist",
    "code": "10s",
    "minAngle": 0.0,
    "maxAngle": 180.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Wrist",
    "code": "4s",
    "minAngle": 0.0,
    "maxAngle": 180.0,
    "initialAngle": 180.0,
  },
  {
    "name": "Rotation",
    "code": "11s",
    "minAngle": 0.0,
    "maxAngle": 180.0,
    "initialAngle": 180.0,
  },
  {
    "name": "Rotation",
    "code": "5s",
    "minAngle": 0.0,
    "maxAngle": 180.0,
    "initialAngle": 90.0,
  },
  {
    "name": "Claps",
    "code": "12s",
    "minAngle": 50.0,
    "maxAngle": 120.0,
    "initialAngle": 50.0,
  },
  {
    "name": "Claps",
    "code": "6s",
    "minAngle": 20.0,
    "maxAngle": 90.0,
    "initialAngle": 20.0,
  },
];